// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationCore2.Models.Domain;

namespace WebApplicationCore2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplicationCore2.Models.Domain.PartiesResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PartiesName");

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("WebApplicationCore2.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = 1, Name = "admin" },
                        new { Id = 2, Name = "user" }
                    );
                });

            modelBuilder.Entity("WebApplicationCore2.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int?>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Name = "admin@mail.ru", Password = "123456", RoleId = 1 }
                    );
                });

            modelBuilder.Entity("WebApplicationCore2.Models.Domain.UserParties", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("PartieId");

                    b.HasKey("UserId", "PartieId");

                    b.HasIndex("PartieId");

                    b.ToTable("UserParties");
                });

            modelBuilder.Entity("WebApplicationCore2.Models.Domain.User", b =>
                {
                    b.HasOne("WebApplicationCore2.Models.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("WebApplicationCore2.Models.Domain.UserParties", b =>
                {
                    b.HasOne("WebApplicationCore2.Models.Domain.PartiesResponse", "PartiesResponse")
                        .WithMany("UserParties")
                        .HasForeignKey("PartieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplicationCore2.Models.Domain.User", "User")
                        .WithMany("UserParties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
